# An RNA string is a string formed from the alphabet containing 'A', 'C', 'G', and 'U'.

# Given a DNA string t
#  corresponding to a coding strand, its transcribed RNA string u
#  is formed by replacing all occurrences of 'T' in t
#  with 'U' in u
# .

# Given: A DNA string t
#  having length at most 1000 nt.

# Return: The transcribed RNA string of t


def transcribe(dna_seq):

    """Takes a sequence of DNA nucleotides and changes them into an RNA sequence
    by replacing T with U"""
    dna_upper = dna_seq.upper()
    rna_seq = dna_upper.replace('T', 'U')

    return rna_seq


if __name__ == "__main__":
    assert transcribe('T') == 'U'
    assert transcribe('GATGGAACTTGACTACGTAAATT') == 'GAUGGAACUUGACUACGUAAAUU'
    print ('All tests are passesd')

    rna = transcribe('CTAACCTAAATGACCGGTTAGAGCACGCTGGCGGCGACCCTTGCACAGGTGTGAATTACATCGGGGGGACCCGAAAGGGAGAGCCCCATACGGGAGAGAGACACCTTTCAACATTTAGAGGTGAATATTCGTCCATCGTGCGTGTCCTAACGAAAGTAGTGGCGAGACCCTGCCGCACGATGATCAGAATTATCGCCTAACGCCGGCCATCGTCATGGGTACCTAAGGTAAGGACGGCCATTCAGAGTAAGTGTCCCTCAAGGTTTGTAACGGGATGGAATTGTAGTCGGGAGAGCGGTGCCCAGGTCGTACTCGACCGCATCGAATGGCTTAGAGCACTAGGAGGCCGCCACAGAACACGGGAACGACAACCTTGAAGTTGGTCTTCAACGCATCTCTACCGCGCTTCTCCTAGTCTCCAACCCTCAGTTCCCTACGACGTAGGTATGTTAGTACTGCGGGCACGCGCTGGATTAGGTGCAGAGTTAAACGCTCGGCCGAACATTTGGATAGGCTCTCGGTATCTACGCTCAAGAAGCTCGTCACTTCTCGAGGTGCCGGGGCTAATTTCTCCTTTGAAAATGGGTGGGGGGATTGGATCGGTCATTCTTTGCTACATTCTAGAGAACCTTAGGTGCGTCGGCACCTGCGAGCAAGGCCAGTTTCGGTAGCTATCAAAACCTCGATAAGTCCACATTGCGGTATCGGCGAGAATCACAACCTAGAGACGTAGTTCTTTTATACATCCCATCAGAACATTATTGTTATTGGGGTTTATGGGCAAGGCTATTTACGCCGCGACATGATGGGGATGTAGCCTGCGAGCGACAGGTGAGGGCCTTACAATTGTGCCGATTGACGCTGGCATCGTGGGGCACAGGCGTACTAGCCACAGTCCTTACGGAAGCCCTATAAACACGTTCCCCACCCACGTCTTATTCACGCACATTAAGC')

    print(rna)
